on:
  push:
  workflow_dispatch:

jobs:
  R-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install dependencies
        shell: Rscript {0}
        run: install.packages(c("fs", "wand"))

      - name: Run a one-line script
        shell: Rscript --vanilla --verbose {0}
        run: source("run.R", echo = TRUE)
