on:
  push:
  workflow_dispatch:

jobs:
  R-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install dependencies
        shell: Rscript {0}
        run: install.packages(c("fs", "wand"))

      - name: Run a one-line script
        shell: Rscript {0}
        run: source("run.R")

      - name: Run a R shell
        shell: R --vanilla {0}
        run: |
          saveRDS("xxx", "xxx.rds")
          Sys.which("file")
          fs::file_access(Sys.which("file"), mode = "execute")
          system2(command = Sys.which("file"), args = c("-b", "--mime-encoding", shQuote("xxx.rds")), stdout = TRUE)
          wand::get_content_type("xxx.rds")
